<div id="nav">
<h3><b>Menu</b></h3>
<ul>
<li><a href = "https://cdn.rawgit.com/priyanka-bitra/BookHub/b7998a02/CreatePost.html">Sell a Book</a></li>
<li><a href = "https://cdn.rawgit.com/priyanka-bitra/BookHub/b7998a02/displayBookPage.html">Buy a Book</a></li>
<li><a href = "https://cdn.rawgit.com/priyanka-bitra/BookHub/b7998a02/AccountInfo.html">Account Information</a></li>
<li><a href = "https://cdn.rawgit.com/priyanka-bitra/BookHub/ee48aab5/login.html">Logout</a></li>
</ul>
</div>
